# Generated by Django 2.2.7 on 2019-11-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_lineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='street_address1',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='street_address2',
        ),
        migrations.AddField(
            model_name='charge',
            name='address',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
