# Generated by Django 2.2.4 on 2019-11-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='prescription',
        ),
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
