# Generated by Django 2.2.4 on 2019-11-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191111_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='postal_code',
            field=models.IntegerField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='telephone',
            field=models.IntegerField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=122),
        ),
    ]
