# Generated by Django 2.2.4 on 2019-11-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191111_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='postal_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
