# Generated by Django 2.2.4 on 2019-11-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191111_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='postal_code',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='telephone',
            field=models.IntegerField(max_length=12),
        ),
    ]
