# Generated by Django 2.2.4 on 2019-11-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191111_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='postal_code',
        ),
    ]
