# Generated by Django 2.2.4 on 2019-11-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_myuser_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='telephone',
        ),
    ]
