# Generated by Django 2.2.4 on 2019-11-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_myuser_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='postal_code',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='telephone',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
