# Generated by Django 2.2.4 on 2019-11-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191111_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='telephone',
            field=models.CharField(max_length=12),
        ),
    ]
