# Generated by Django 2.2.7 on 2019-11-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='done',
        ),
    ]
