# Generated by Django 2.2.7 on 2019-11-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalise', '0002_remove_item_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='personalise',
        ),
    ]
